export let products = [
  {
    id: "1",
    title: "Pikachu",
    price: "$ 150",
    stock: 10,
    imageUrl: "s",
    description: "Pokemon ratón",
    category: "pokemon",
  },
  {
    id: "2",
    title: "Eevee",
    price: "$ 150",
    stock: 15,
    imageUrl: "s",
    description: "Pokemon zorro",
    category: "pokemon",
  },
  {
    id: "3",
    title: "Meowth",
    price: "$ 130",
    stock: 5,
    imageUrl: "s",
    description: "Pokemon gato",
    category: "pokemon",
  },
  {
    id: "4",
    title: "Marill",
    price: "$ 120",
    stock: 13,
    imageUrl: "s",
    description: "Pokemon ratón",
    category: "pokemon",
  },
  {
    id: "5",
    title: "Pokeball",
    price: "$ 10",
    stock: 100,
    imageUrl: "s",
    description: "Pokeball común",
    category: "pokeballs",
  },
  {
    id: "6",
    title: "Superball",
    price: "$ 30",
    stock: 70,
    imageUrl: "s",
    description: "Pokeball mejorada",
    category: "pokeballs",
  },
  {
    id: "7",
    title: "Ultraball",
    price: "$ 50",
    stock: 65,
    imageUrl: "s",
    description: "Pokeball ultra mejorada",
    category: "pokeballs",
  },
  {
    id: "8",
    title: "Poción",
    price: "$ 20",
    stock: 40,
    imageUrl: "s",
    description: "Remedio que recupera 20 puntos de vida de tu pokemon",
    category: "objetos",
  },
  {
    id: "9",
    title: "Superpoción",
    price: "$ 50",
    stock: 40,
    imageUrl: "s",
    description: "Remedio que recupera 50 puntos de vida de tu pokemon",
    category: "objetos",
  },
  {
    id: "10",
    title: "Hiperpoción",
    price: "$ 80",
    stock: 25,
    imageUrl: "s",
    description: "Remedio que recupera 200 puntos de vida de tu pokemon",
    category: "objetos",
  },
];
